### ISSUE TITLE
qt-based wayland images of bullseye branch are not starting correctly due to missing bash

### ISSUE THREAD

**Issue by MarcusGrum** [toradex/debian-docker-images#1]
Your qt-based wayland images, such as the ones created with `qt5-wayland-examples/Dockerfile` coming from the bullseye branch are not starting due to a missing bash. 

When following your [QT Debian for Torizon](https://developer.toradex.com/knowledge-base/qt-debian-container-for-torizon#3-32-bit-socs-arm32v7) tutorial and starting the weston container with
`docker run -d --rm --name=weston --net=host --cap-add CAP_SYS_TTY_CONFIG \
             -v /dev:/dev -v /tmp:/tmp -v /run/udev/:/run/udev/ \
             --device-cgroup-rule='c 4:* rmw' --device-cgroup-rule='c 13:* rmw' --device-cgroup-rule='c 226:* rmw' \
              torizon/weston:$CT_TAG_WESTON --developer weston-launch --tty=/dev/tty7 --user=torizon`
and starting the qt container with
`# docker run --rm -it --name=qt5 \
             -v /tmp:/tmp \
             -v /dev/dri:/dev/dri --device-cgroup-rule='c 226:* rmw' \
             torizon/qt5-wayland-examples:$CT_TAG_QT5_WAYLAND_EXAMPLES`
these for instance result in 
`torizon/qt5-wayland-examples->docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"|1\": executable file not 		found in $PATH": unknown.`

The current workaround:
`docker run --rm -it --entrypoint=bash --name=qt5-14-2 \
             -v /tmp:/tmp \
             -v /home/torizon/:/home/torizon/ \
             -v /dev/dri:/dev/dri --device-cgroup-rule='c 226:* rmw' \
             torizon/qt5-wayland-examples:$CT_TAG_QT5_WAYLAND_EXAMPLES`
which considers the flag `--entrypoint=bash`. But obviously this is not intended by you since all the images having `$CT_TAG_QT5_WAYLAND_EXAMPLES=1` and other branches having `$CT_TAG_QT5_WAYLAND_EXAMPLES=2` are starting correctly as described in the tutorial.

**Comment by VMinute** [comment]
Currently our containers won't start bash as default, we are working on this.
In the meantime you can add "bash" as command after the container name, as suggested in our documentation. This will allow you to access the shell prompt as usual.
Sorry for the inconvenience.
